### ISSUE TITLE
live share

### ISSUE THREAD

**Issue by Coderilz** [dg-ilyas/D-G-sentiment#3]
https://prod.liveshare.vsengsaas.visualstudio.com/join?DC84F7E7887523754F4084693D8372A6EB8C

**Comment by Coderilz** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?679677815CD783FCF815CA30FDAA84670ED8

**Comment by Coderilz** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?62BF0F4EBED9EA37AD92082FC2B29BED757F

**Comment by Coderilz** [comment]
Traceback (most recent call last):
  File "C:\Users\06\Documents\repos\D-G-sentiment\sentiment.py", line 23, in <module>
    response = comprehend.detect_sentiment(Text=comment_body, LanguageCode='en')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\06\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\botocore\client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the DetectSentiment operation: The security token included in the request is invalid.

**Comment by Coderilz** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?5B1658C35F2CD57A75BE92FBB04BCF69513C

**Comment by Coderilz** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?77DA296F39AC4694F7AB79C3592BE0681049

**Comment by Coderilz** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?4B68F9D70961CFA28A706C7D60137BD9229C
